DROP TABLE IF EXISTS EMP;

DROP TABLE IF EXISTS DEPT;

CREATE TABLE DEPT(  
  DEPTNO     NUMBER(2,0),  
  DNAME      VARCHAR2(14),  
  LOC        VARCHAR2(13),  
  CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)  
);
  
CREATE TABLE EMP (
  EMPID INT,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) DEFAULT NULL,
  DEPTNO   NUMBER(2,0),
  CONSTRAINT PK_EMP PRIMARY KEY (EMPID),
  CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO)
);

INSERT INTO DEPT VALUES(10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES(20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES(30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES(40, 'OPERATIONS', 'BOSTON');


